---
# tasks file for zabbix-role

- name: Add paquet Zabbix
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    state: installed 

- name: install Zabbix server-mysql
  yum:
    name: zabbix-server-mysql
    state: installed

- name: install Zabbix Web
  yum:
    name: zabbix-web-mysql
    state: installed

- name: Import data with zabbix-server in mysql-db
  shell: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -p zabbix
  ignore_errors: yes
  args:
    warn: no

- name: configuaration database for zabbix
  template:
    src: roles/zabbix/templates/zabbix_server.j2
    dest: "/etc/zabbix/zabbix_server.conf"
    owner: centos
    remote_src: no

- name: Start service zabbix-server
  service:
    name: zabbix-server
    state: started

- name: Enable service zabbix
  service:
    name: zabbix-server
    enabled: yes

- name: configuaration interface web zabbix
  template:
    src: roles/zabbix/templates/zabbix.j2
    dest: "/etc/httpd/conf.d/zabbix.conf"
    owner: centos
    remote_src: no

- name: Configuration SELinux 1
  shell: setsebool -P httpd_can_connect_zabbix on
  args:
    warn: no

- name: Configuration SELinux 2
  shell: setsebool -P httpd_can_network_connect_db on
  args:
    warn: no

- name: Restart service httpd
  service:
    name: httpd
    state: restarted

- name: Installation zabbix-agent
  yum:
    name: zabbix-agent
    state: installed

- name: configuaration zabbix-agent
  template:
    src: roles/zabbix/templates/zabbix_agent.j2
    dest: "/etc/zabbix/zabbix_agent.conf"
    owner: centos
    remote_src: no

- name: Start service zabbix-agent
  service:
    name: zabbix-agent
    state: started
